### ISSUE TITLE
Add topics to respository

### ISSUE THREAD

**Issue by nuest** [eddelbuettel/ctv-hpc#13]
Please consider adding the ["topics"](https://github.com/blog/2309-introducing-topics)

`cran`, `task-view` (and maybe more, ... [`hpc`](https://github.com/topics/hpc)?)

to join the existing task views on GitHub under the URL https://github.com/topics/task-view

**Comment by eddelbuettel** [comment]
Done :)

**Comment by eddelbuettel** [comment]
`task-view` is questionable though as too generic.  Maybe make it `cran-task-view`?  Can you ask whoever at rOpenSci came with this?

**Comment by nuest** [comment]
I made an inquiry: https://discuss.ropensci.org/t/task-views-on-github-consistent-topics/1024?u=nuest

My favourite was `cran-ctv` :-), but the abbreviation might not be so well known, so `cran-task-view` looks best to me.
