### ISSUE TITLE
Information on RNG for parallel packages

### ISSUE THREAD

**Issue by ChandlerLutz** [eddelbuettel/ctv-hpc#20]
Some links to random number generation for parallel computing may be helpful, especially for new users. 

* SO answer: https://stackoverflow.com/a/21568878/1317443
* Rstudio Pub: https://rpubs.com/Jouni_Helske/225931

**Comment by eddelbuettel** [comment]
Good point. I used to post about that too on r-sig-hpc and had slides in my older presentations.  (And I was the one pointing Joini to the [sitmo](https://github.com/coatless/sitmo) generator he now uses.)

**Comment by ChandlerLutz** [comment]
Oh, thanks for passing along the sitmo package. I didn't know about that one. Let me know if I can do anything to help.

**Comment by eddelbuettel** [comment]
Trouble with your two links is ... that the Task Views generally do not turn into tutorials or vignettes.  That said, a tutorial may make sense at the [Rcpp Gallery](http://gallery.rcpp.org).  Do  you want to draft something, maybe with a paralllel / multicore example?

**Comment by eddelbuettel** [comment]
But I added sitmo now--that was overdue.

**Comment by ChandlerLutz** [comment]
Okay, thanks. I'll work on the tutorial and get back to you

**Comment by rstub** [comment]
@ChandlerLutz Are you interested in a cooperation w.r.t. the tutorial? I have uploaded v0.0.4 of the dqrng package today that now includes a [new vignette](https://cran.r-project.org/web/packages/dqrng/vignettes/parallel.html) on the subject and could be (partially) reused.

**Comment by ChandlerLutz** [comment]
@rstub Sorry for the late reply. I would love to collaborate. Could you send me an email at cl.eco at cbs.dk ?? I have some resources that we may want to use and I would like to discuss further.
