### ISSUE TITLE
Adding spark(lyr) to the taskview

### ISSUE THREAD

**Issue by nlbjan1** [eddelbuettel/ctv-hpc#26]
Would it make sense to add Spark related packages (such as sparklyr) to the task view?

**Comment by eddelbuettel** [comment]
I don't think of that as HPC. And I believe the planet as a whole has enough people hyping ~Hadoop,~ Spark and whatever other flavour is currently en vogue.

(There is some bitterness in this in the sense of [this essay](https://www.dursi.ca/post/hpc-is-dying-and-mpi-is-killing-it.html).) 

So if you *really* think it must be there send a clean PR.  I for one think we can move on without it.

**Comment by nlbjan1** [comment]
I don't feel strongly about it.
