### ISSUE TITLE
Suggestion: profile and proffer

### ISSUE THREAD

**Issue by wlandau** [eddelbuettel/ctv-hpc#29]
Packages [`profile`](https://cran.r-project.org/package=profile) and [`proffer`](https://cran.r-project.org/package=proffer) help process and visualize profiling data, respectively. May I submit a PR to include them in the task view?

**Comment by eddelbuettel** [comment]
Not a bad idea. Coincidentally, [xrprof](https://github.com/atheriel/xrprof) entered the scene and would likely need to be added.  

Maybe we can draft something covering all three?

**Comment by wlandau** [comment]
Sounds good, I [drafted some new entries](https://github.com/wlandau/ctv-hpc/blob/de6d7af49af1f2e1a6e8874c183fde7b9184a45b/HighPerformanceComputing.ctv#L595-L612):

```xml
      <li>
        The <pkg>profile</pkg> package establishes a data structure
        for profiling output, and it processes
        <a href="https://github.com/google/pprof"><code>pprof</code></a>
        and <code>Rprof</code> and files.
      </li>
      <li>
        The <pkg>proffer</pkg> package is an interface to visualize
        <code>Rprof</code> and <code>pprof</code> data using Google's
        <a href="https://github.com/google/pprof"><code>pprof</code></a> utility.
      </li>
      <li>
        The <code>xrprof</code> command line tool uses <code>ptrace</code>
        to profile external R processes that are already running.
        The output includes calls to C/C++ functions, and visualization
        is possible through
        <a href = "http://www.brendangregg.com/flamegraphs.html"><code>FlameGraph</code></a>.
      </li>
```

What is the inclusion/exclusion policy for tools like `xrprof` that are not structured as R packages and are not on CRAN?

**Comment by eddelbuettel** [comment]
See the bottom of the ctv file---there always have been external tools as `slurm` or `pprof` or .... are not on CRAN.

So basic editorial choice:  does it add value? If so we include it.  `xprof` likely fits that bill.

**Comment by wlandau** [comment]
Should we link to the `xrprof` GitHub page in the [list item](https://github.com/wlandau/ctv-hpc/blob/ec67917e72ecffbe482e2a72f09bd045aab147f5/HighPerformanceComputing.ctv#L608) and the `<links>` at the bottom?

**Comment by eddelbuettel** [comment]
Should the three paragraphs be one?  As it is all about profiling?  Am on the fence on that: would be "tighter" and more focussed but we don't always do it in other places (but probably should....)

**Comment by wlandau** [comment]
Now that you mention it, there is noticeable repetition. [Here](https://github.com/wlandau/ctv-hpc/blob/9bfd4484a71a21b0745722049bb37ebb9fe3d1e2/HighPerformanceComputing.ctv#L585-L594) is an attempt to condense the list. It also includes `profmem`.

```xml
Packages <pkg>profvis</pkg>, <pkg>proffer</pkg>, <pkg>profmem</pkg>,
<pkg>GUIProfiler</pkg>, <pkg>proftools</pkg>, and <pkg>aprof</pkg>
summarize and visualize output from the <code>Rprof</code>
interface for profiling. The <pkg>profile</pkg> package reads and
writes profiling data and converts among file formats such as
<a href="https://github.com/google/pprof"><code>pprof</code></a>
by Google and <code>Rprof</code>.
The <a href="https://github.com/atheriel/xrprof"><code>xrprof</code></a>
command line tool uses <code>ptrace</code> to profile external R processes
that are already running.
```

**Comment by wlandau** [comment]
By the way, should we also include benchmarking packages like `microbenchmark` and `bench`?

**Comment by eddelbuettel** [comment]
We could. The set is `rbenchmark`, `microbenchmark` and `bench`.  Might be worth a quick new paragraph.

**Comment by eddelbuettel** [comment]
The joint paragraph is good but `xrprof` does not call `ptrace`. 

Maybe just say:  

> The `xprof` command-line tool implements profile sampling for a given R process om Linux or Windows, and can profile R code alongside compiled code.

**Comment by wlandau** [comment]
Added https://github.com/eddelbuettel/ctv-hpc/issues/29#issuecomment-766853640 in a [new branch](https://github.com/wlandau/ctv-hpc/tree/29) with base https://github.com/wlandau/ctv-hpc/commit/ffd2cbe1a13c0b15432ee56c20614efc9745a110.

**Comment by wlandau** [comment]
Do you think [this diff](https://github.com/eddelbuettel/ctv-hpc/compare/master...wlandau:29) is ready for a PR?

**Comment by eddelbuettel** [comment]
Yup. I actually thought we had done that already....

_Edit:_ I clearly had it confused with #32.  Your communications tend to come in waves so I had myself confused :grinning:

**Comment by wlandau** [comment]
Thanks, totally understandable.
