### ISSUE TITLE
Suggestion: update drake description and mention targets

### ISSUE THREAD

**Issue by wlandau** [eddelbuettel/ctv-hpc#30]
[`targets`](https://cran.r-project.org/package=targets), the long-term successor of [`drake`](https://cran.r-project.org/package=drake), just arrived on CRAN. In addition, the description of [`drake`](https://cran.r-project.org/package=drake)'s parallel backends is out of date. May I submit a PR to update this part of the task view?

**Comment by eddelbuettel** [comment]
Sure, good idea.  And appreciate you come knocking here first.  Maybe run a first diff draft by here?  Maybe we can keep it in one paragraph of about the same length?

**Comment by wlandau** [comment]
Thanks, Dirk. I was thinking we might change this:

https://github.com/eddelbuettel/ctv-hpc/blob/5f36d3d0ff4cad8cff795592126f520cd8b71708/HighPerformanceComputing.ctv#L194-L199

to something like [this](https://github.com/wlandau/ctv-hpc/blob/d341b56bbd3ac394e0cefbe34c49600ad5026fe2/HighPerformanceComputing.ctv#L194-L198):

```xml
        The <pkg>targets</pkg> package and its predecessor <pkg>drake</pkg> are R-focused
        pipeline toolkits similar to <a href="https://www.gnu.org/software/make">Make</a>.
        Each constructs a directed acyclic graph representation of the user's workflow
        and orchestrates distributed computing across <code>clustermq</code> and
        <code>future</code> workers.
```

**Comment by eddelbuettel** [comment]
(Minor personal style thing:  I avoid apostrophes like the plague.  So third line maybe just drop _user's_ as it adds nothing?)

**Comment by wlandau** [comment]
Good idea, I just removed a couple in https://github.com/wlandau/ctv-hpc/commit/2d80aca00713c2737477aa89d00bfc806702ef0a and https://github.com/wlandau/ctv-hpc/commit/55a7c21465ca41436264f8bc6bad045c441f2fb7.

**Comment by eddelbuettel** [comment]
In the second case I'd add a '... by Google' to the sentence to keep that bit of information:

<code>Rprof</code> and <code>pprof</code> data using the <a href="https://github.com/google/pprof"><code>pprof</code></a> utility by Google.

**Comment by wlandau** [comment]
Added in https://github.com/wlandau/ctv-hpc/commit/ec67917e72ecffbe482e2a72f09bd045aab147f5.

**Comment by eddelbuettel** [comment]
`xrprof` is (on my side) in flux / waiting, it's author contacted me on Friday and I did some work with it yesterday but have not heard back.  That said, what you drafted there looked good so shall we just knock these two PRs out now (or one PR with both changes for simplicity) ?

**Comment by wlandau** [comment]
I will submit a PR for `targets` and `drake`. After https://github.com/eddelbuettel/ctv-hpc/issues/29#issuecomment-766384833, I am less sure about what I wrote for #29.
