### ISSUE TITLE
Suggestion: add arrow

### ISSUE THREAD

**Issue by iagogv3** [eddelbuettel/ctv-hpc#34]
As the included `disk.frame` package has been discontinued in favour of `arrow` (https://arrow.apache.org/docs/r/index.html), which seems to be suitable for this Cran View

**Comment by eddelbuettel** [comment]
Yes, it is a good idea to add `arrow`.  

(But I do not think the `disk.frame` package is discontinued, it is still [at CRAN at its page](https://cloud.r-project.org/web/packages/disk.frame/index.html) -- though it may have been removed and then re-admitted, this can happen).

**Comment by iagogv3** [comment]
Thanks @eddelbuettel  and sorry for not answering before. When I told `disk.frame` has been discontinued, I meant the announcement in https://github.com/DiskFrame/disk.frame that

> **{disk.frame} has been soft-deprecated in favor of {arrow}**
