### ISSUE TITLE
Add link to GitHub page (info line)

### ISSUE THREAD

**Issue by HenrikBengtsson** [eddelbuettel/ctv-hpc#5]
Would you mind adding https://cran.r-project.org/web/views/HighPerformanceComputing.html to the GitHub info line next to "CRAN Task View: High-Performance Computing with R"?

**Comment by eddelbuettel** [comment]
You mean in the meta data for this repo?

**Comment by HenrikBengtsson** [comment]
Yes, the "Website" field.  Provides an easy way to get to the CRAN Taskview page from the GitHub page.

**Comment by eddelbuettel** [comment]
That's what I thought you meant.  I think I've done that.
