### ISSUE TITLE
Section Parallel computing Applications: outdated and incomplete

### ISSUE THREAD

**Issue by HenrikBengtsson** [eddelbuettel/ctv-hpc#6]
The Section 'Parallel computing: Applications' lists various ("random") R packages that in one way or the other (optionally) uses a parallel backend.

First, several of the listed packages have outdated information, e.g.

> The partDSA package uses nws for generating a piecewise constant estimation list of increasingly complex predictors based on an intensive and comprehensive search over the entire covariate space.

This package no longer uses nws, but parallel.

More importantly, what is the point of this section?  If we would list all packages that can run things in parallel, this section would become very large and it would require lots of maintenance.

I suggest to scrap it.  It could be that a few of the entries warrants a place elsewhere on the page.

**Comment by HenrikBengtsson** [comment]
closed w/out comment ?

**Comment by eddelbuettel** [comment]
Yes. I am always open to constructive comment.  This, however, didn't clear the bar.

**Comment by HenrikBengtsson** [comment]
I think I made it clear that the section is outdated.  I could propose it needs to be updated, and have new packages added, but I argued that's would become overwhelming work.  Therefore I proposed to drop it with the question: "what's the point of the section?".  Isn't that enough for starting a discussion?

**Comment by eddelbuettel** [comment]
There are an unlimited number of things that "suck" and a very large number of things that are more important.  You made the effort of pointing something out we both already knew, but have moved the needle exactly zero inches.  We are both wasting our time in this thread.  Sorry but still closed.
